### ISSUE TITLE
Add note about typical URL for materials

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#1]
In a couple of sessions I've found that people asked where to get the slides.  The URL is of the format:

https://datatracker.ietf.org/meeting/91/materials.html#v6ops

where the "#v6ops" is the WG name.  (The https://datatracker.ietf.org/meeting/91/materials.html page does not have a TOC showing these names, they _are_ in the page and so you can jump to them.)

While the draft suggests having a tab open for the materials page, perhaps we add an explicit mention that the materials URL takes the above form.

**Comment by stpeter** [comment]
That works until the format changes. :-) However, we can say something to the effect of "at the time of writing". Also these URLs are available via the tools-style agendas, in my experience.

**Comment by stpeter** [comment]
Added.
