### ISSUE TITLE
Add something about adding the Note Well

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#11]
Feedback from Olle Johansson:

---

Thank you for a great document!

I think a section about the requirement to add the note well should be taken into consideration.

There was a discussion about this on one of the generic mailing lists after London. I had a participant that wanted to participate anonymously without accepting the note well,
which led to a discussion. I think it's important that we make a decision and document it in this document - there may already be a decision.

**Comment by stpeter** [comment]
I think it's not for this document to make such a decision. However, there are plans afoot to have the chatroom automatically send the Note Well notice to new participants when they join the chatroom, which might alleviate some concerns.
