### ISSUE TITLE
Add trouble email addresses scribes may care about

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#3]
Chatroom relays may want to communicate to the NOC about issues being reported by remote participants. For example, low (or no) audio levels or issues with Meetecho.

It may be useful to add a new section to the draft so that this information is in one place for any scribe/relay.  Perhaps a section called "Reporting Trouble" with info culled from the info below.

From Ray Pelletier:

```
Network & Audio Streaming Issues:       tickets@meeting.ietf.org
Meeting Trouble Desk (all other Issues):    mtd@ietf.org 
```

From Jim Martin:

== NOC and Ticketing ==

There are several ways to communicate with the NOC staff. 
1. Submit a new trouble ticket via the [http://tickets.meeting.ietf.org/newticket "trac web"] interface. Filling in the following fields: "My MAC Address", "My Current Location", and "My OS" may expedite ticket processing. If you have an existing account on http://tools.ietf.org you can use your established credentials (email address and tools password) to [http://tickets.meeting.ietf.org/login "log in"].
2. Send an email to '''`tickets@meeting.ietf.org`''' with as much detail regarding your issue and configuration as possible. 
3. If you're on site and need direct network assistance (i.e - you have no network) please go to the helpdesk, which is located in the Terminal Room.
4. Use the Jabber room at noc @ jabber.ietf.org to report issues or communicate with the NOC.

**Comment by stpeter** [comment]
Yes, let's work this in.

**Comment by stpeter** [comment]
Added.
