### ISSUE TITLE
Add suggestion about running a second jabber client?

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#4]
It occurred to me that in the past when I have done heavy jabber scribing of a session I have occasionally ran into an issue where my jabber client had a problem and I was unable to write anything into the chat.  Typically this has been an issue with connectivity to the jabber server (or the server having uptime issues).  Once it was a problem with my chat client dying for some reason.

The challenge is that the jabber room then has no clue that I've had a technical problem and am no longer in the room.  I've had people asking for a relay but I've not been able to answer.

My "solution" when I have been planning to do heavy jabber scribing has been to have two jabber clients running on my laptop.  One is in the chat room and is the one I use.  The other one is running on my laptop and is _connected to a **different** jabber server_.  If the first one fails, the second one can join the chat room and be able to update the room or resume jabber scribing.

Obviously there are other "solutions", including:
- Going to the mic and saying on the audio stream that I'm having a challenge and asking someone else to help.
- Asking someone I know who is sitting nearby to help out in the room (or at least alert them).

But the question is whether adding the two-client "solution" to the draft is a worthwhile suggestion... or just something way too geeky to be added.

**Comment by stpeter** [comment]
I don't think it hurts to mention. Defense in depth. :-)

**Comment by stpeter** [comment]
Added a bullet point on this.
