### ISSUE TITLE
Feedback from Dave Crocker

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#5]
Dave provided the following comments:

`A chatroom relay is often referred to as a "Jabber scribe".  This
  term is misleading because nothing prevents the IETF from using a
  technology other than Jabber/XMPP [RFC6120] [XEP-0045] for chatrooms
  (say, IRC or an integrated collaboration environment), and more
  importantly because volunteers are not expected to scribe the
  complete contents of the meeting into the chatroom (which would be a
  much more onerous task than relaying selected information back and
  forth between the physical room and the chatroom).  Use of the term
  "scribe" might discourage people from volunteering to serve in the
  role.`

While valid, I think everything after the first sentence is distracting.

I suggest keeping this doc on a "how to" level, rather than discussing
abstractions.

```
The participants in a chatroom typically fall into three categories:
```

I think it could be helpful to label these guys, so:

Remote Participant:
 `o  Remote attendees who are listening to the audio stream or in some
     cases following the proceedings using a real-collaboration system
     (currently exemplified by the MeetEcho service).  These
     participants might wish to send questions or feedback to the
     physical room.`

Observer:
`o  IETF meeting attendees who are in another simultaneous session in
     a different physical room.  These participants are often
     monitoring the chatroom session to find out when a particular
     topic is being discussed or to observe what is being discussed in
     the chatroom.  Typically they are not able to listen to the audio
     stream and sometimes they ask for a higher level of commentary so
     that they can know when they might need to change locations to
     participate in the session's physical room.`

Local Participant:
 `o  IETF meeting attendees who are in the same session.  These
     participants like to follow the discussions in the physical room
     and the chatroom at the same time.  They can also provide some
     assistance to chatroom relays.`

**Comment by stpeter** [comment]
Hey, I'm the Jabber guy, so it might be in my interest to keep that terminology. However, I do find the term "jabber" misleading (vs. some other tech) and more importantly the term "scribe" scares away volunteers ("oh no, I'll need to type every word people say"). "Chatroom Relay" is more friendly. But perhaps it's too late for me to reform the existing usage.

Naming those roles seems fine.

**Comment by stpeter** [comment]
Feedback incorporated.
