### ISSUE TITLE
Mention how to find the chatroom for the working group

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#6]
A reviewer noted that we don't explain how to get into the chat room for the working group.  On one level that is perhaps just something we should assume... but it might be useful to add a bullet to section 5.2 ("As The Session Is Starting") that says something about "join the jabber chat room for the session" and explain that jabber chat rooms are usually <wg>@jabber.ietf.org

**Comment by stpeter** [comment]
Suggested text:

   o  Start up your preferred Jabber client, log into your server, and
      join the chatroom for your session; the addresses are of the form
      wg-name@jabber.ietf.org or bof-name@jabber.ietf.org.
