### ISSUE TITLE
New section on "As The Session Is Ending"

### ISSUE THREAD

**Issue by danyork** [stpeter/chatroom-relay#8]
I realized that the current document has sections:
- 5.1 Before The Session
- 5.2 As The Session Is Starting
- 5.3 During The Session

but has nothing about ending the session.  Perhaps we add an "As The Session Is Ending" section with the suggestions:
- Communicate that the session is finishing up and ask if there are any final comments for relay.
- Indicate that you are leaving the Jabber room and no one will be available for any further relay.

**Comment by stpeter** [comment]
Provisional text:

5.4.  As the Session Is Ending

   As you wrap up your scribing at the end of the session:

   o  Post a message into the chatroom informing all of the participants
      that the session is finishing up, and ask for any final comments
      to be relayed.

   o  When the session is done, say so in the chatroom.

   o  Indicate that you are leaving the Jabber room and that no one will
      be available relay further comments.
